import {Engine} from './engine.js';import {buildWorld} from './world.js';import {buildAircraft} from './aircraft.js';import {Flight} from './flight.js';
const canvas=document.querySelector('#gl'),boot=document.querySelector('#boot'),hud=document.querySelector('#hud'),play=document.querySelector('#play'),speedEl=document.querySelector('#speed'),altEl=document.querySelector('#alt'),hdgEl=document.querySelector('#hdg'),thrEl=document.querySelector('#thr'),camBtn=document.querySelector('#cameraBtn'),msg=document.querySelector('#msg');
let engine,flight,aircraft,started=false,last=performance.now(),camMode=0,drag=false,camYaw=0,camPitch=.22,camDist=48;
function toast(s){msg.textContent=s;msg.classList.add('show');setTimeout(()=>msg.classList.remove('show'),1500)}
function init(){engine=new Engine(canvas);buildWorld(engine);flight=new Flight();aircraft=buildAircraft(engine,flight);started=true;boot.classList.add('hidden');hud.classList.remove('hidden');toast('Skybound 3D engine ready');requestAnimationFrame(loop)}
function loop(now){const dt=Math.min(.033,(now-last)/1000);last=now;flight.update(dt);updateCamera(dt);engine.render(now/1000);speedEl.textContent=Math.round(flight.knots);altEl.textContent=Math.max(0,Math.round(flight.feet));hdgEl.textContent=String((Math.round(((-flight.yaw*180/Math.PI+90)%360+360)%360))).padStart(3,'0');thrEl.textContent=Math.round(flight.throttle*100);requestAnimationFrame(loop)}
function updateCamera(){const p=flight.pos,cy=Math.cos(flight.yaw),sy=Math.sin(flight.yaw);if(camMode===0){const back=camDist,side=Math.sin(camYaw)*back*.45,up=13+camPitch*28;engine.cam=[p[0]-cy*back+sy*side,p[1]+up,p[2]+sy*back+cy*side];engine.target=[p[0]+cy*16,p[1]+3,p[2]-sy*16]}else{engine.cam=[p[0]+cy*12,p[1]+2.1,p[2]-sy*12];engine.target=[p[0]+cy*140,p[1]+Math.sin(flight.pitch)*90,p[2]-sy*140]}}
play.addEventListener('click',()=>{if(!started)try{init()}catch(e){boot.innerHTML='<div class="brand">SKYBOUND <span>ERROR</span></div><p style="max-width:600px;color:#ffb6b6">'+e.message+'</p>'}});
camBtn.addEventListener('click',()=>{camMode=(camMode+1)%2;camBtn.textContent='CAM: '+(camMode?'COCKPIT':'CHASE')});
addEventListener('keydown',e=>{if(e.code==='KeyC'&&started)camBtn.click();if(e.code==='KeyR'&&started){flight.reset();toast('Aircraft reset')}});
canvas.addEventListener('pointerdown',e=>{drag=true;canvas.setPointerCapture(e.pointerId)});canvas.addEventListener('pointerup',()=>drag=false);canvas.addEventListener('pointermove',e=>{if(!drag||camMode!==0)return;camYaw-=e.movementX*.006;camPitch=Math.max(-.15,Math.min(.75,camPitch-e.movementY*.004))});canvas.addEventListener('wheel',e=>{camDist=Math.max(24,Math.min(90,camDist+e.deltaY*.035));e.preventDefault()},{passive:false});
