import {M4} from './math.js';
const VS=`#version 300 es
precision highp float;layout(location=0)in vec3 aPos;layout(location=1)in vec3 aNormal;uniform mat4 uM,uV,uP;out vec3 vN;out vec3 vW;void main(){vec4 w=uM*vec4(aPos,1.);vW=w.xyz;vN=mat3(uM)*aNormal;gl_Position=uP*uV*w;}`;
const FS=`#version 300 es
precision highp float;in vec3 vN;in vec3 vW;uniform vec3 uColor,uSun,uCam;uniform float uFog;out vec4 o;void main(){vec3 n=normalize(vN);float d=max(dot(n,normalize(uSun)),0.0);float hemi=.38+.42*max(n.y,0.0);float spec=pow(max(dot(reflect(-normalize(uSun),n),normalize(uCam-vW)),0.0),24.0)*.16;vec3 col=uColor*(hemi+d*.62)+spec;float dist=length(uCam-vW);float f=1.0-exp(-dist*uFog);vec3 fog=vec3(.62,.79,.88);o=vec4(mix(col,fog,clamp(f,0.,.88)),1.);}`;
const OVS=`#version 300 es
precision highp float;layout(location=0)in vec3 aPos;uniform mat4 uV,uP;uniform vec3 uCam;uniform float uTime;out float wave;void main(){vec3 p=aPos;p.y+=sin((p.x+uTime*55.)*.003)*1.6+cos((p.z-uTime*45.)*.0024)*1.2;wave=p.y;gl_Position=uP*uV*vec4(p,1.);}`;
const OFS=`#version 300 es
precision highp float;in float wave;out vec4 o;void main(){float a=.42+wave*.018;o=vec4(.025,.27+.05*a,.40+.08*a,1.);}`;
function shader(gl,t,s){const h=gl.createShader(t);gl.shaderSource(h,s);gl.compileShader(h);if(!gl.getShaderParameter(h,gl.COMPILE_STATUS))throw Error(gl.getShaderInfoLog(h));return h}
function prog(gl,v,f){const p=gl.createProgram();gl.attachShader(p,shader(gl,gl.VERTEX_SHADER,v));gl.attachShader(p,shader(gl,gl.FRAGMENT_SHADER,f));gl.linkProgram(p);if(!gl.getProgramParameter(p,gl.LINK_STATUS))throw Error(gl.getProgramInfoLog(p));return p}
export class Engine{
 constructor(canvas){this.c=canvas;this.gl=canvas.getContext('webgl2',{antialias:true,alpha:false});if(!this.gl)throw Error('WebGL 2 unavailable');const g=this.gl;this.p=prog(g,VS,FS);this.op=prog(g,OVS,OFS);this.meshes=[];this.ocean=null;this.cam=[0,30,80];this.target=[0,0,0];this.fog=.00008;g.enable(g.DEPTH_TEST);g.enable(g.CULL_FACE);g.clearColor(.61,.79,.89,1)}
 makeMesh(pos,norm,idx){const g=this.gl,vao=g.createVertexArray();g.bindVertexArray(vao);const vb=g.createBuffer();g.bindBuffer(g.ARRAY_BUFFER,vb);g.bufferData(g.ARRAY_BUFFER,new Float32Array(pos),g.STATIC_DRAW);g.enableVertexAttribArray(0);g.vertexAttribPointer(0,3,g.FLOAT,false,0,0);const nb=g.createBuffer();g.bindBuffer(g.ARRAY_BUFFER,nb);g.bufferData(g.ARRAY_BUFFER,new Float32Array(norm),g.STATIC_DRAW);g.enableVertexAttribArray(1);g.vertexAttribPointer(1,3,g.FLOAT,false,0,0);const ib=g.createBuffer();g.bindBuffer(g.ELEMENT_ARRAY_BUFFER,ib);g.bufferData(g.ELEMENT_ARRAY_BUFFER,new Uint32Array(idx),g.STATIC_DRAW);g.bindVertexArray(null);return{vao,count:idx.length}}
 add(mesh,color,transform=()=>M4.identity()){const o={mesh,color,transform,visible:true};this.meshes.push(o);return o}
 setOcean(mesh){this.ocean=mesh}
 resize(){const d=Math.min(devicePixelRatio||1,2),w=Math.max(2,innerWidth*d|0),h=Math.max(2,innerHeight*d|0);if(this.c.width!==w||this.c.height!==h){this.c.width=w;this.c.height=h}this.gl.viewport(0,0,w,h)}
 render(t){this.resize();const g=this.gl;g.clear(g.COLOR_BUFFER_BIT|g.DEPTH_BUFFER_BIT);const asp=this.c.width/this.c.height,P=M4.perspective(Math.PI/3,asp,.3,120000),V=M4.lookAt(this.cam,this.target);if(this.ocean){g.useProgram(this.op);g.uniformMatrix4fv(g.getUniformLocation(this.op,'uV'),false,V);g.uniformMatrix4fv(g.getUniformLocation(this.op,'uP'),false,P);g.uniform3fv(g.getUniformLocation(this.op,'uCam'),this.cam);g.uniform1f(g.getUniformLocation(this.op,'uTime'),t);g.bindVertexArray(this.ocean.vao);g.drawElements(g.TRIANGLES,this.ocean.count,g.UNSIGNED_INT,0)}g.useProgram(this.p);g.uniformMatrix4fv(g.getUniformLocation(this.p,'uV'),false,V);g.uniformMatrix4fv(g.getUniformLocation(this.p,'uP'),false,P);g.uniform3fv(g.getUniformLocation(this.p,'uSun'),[.35,.85,.2]);g.uniform3fv(g.getUniformLocation(this.p,'uCam'),this.cam);g.uniform1f(g.getUniformLocation(this.p,'uFog'),this.fog);for(const o of this.meshes){if(!o.visible)continue;g.uniformMatrix4fv(g.getUniformLocation(this.p,'uM'),false,o.transform());g.uniform3fv(g.getUniformLocation(this.p,'uColor'),o.color);g.bindVertexArray(o.mesh.vao);g.drawElements(g.TRIANGLES,o.mesh.count,g.UNSIGNED_INT,0)}g.bindVertexArray(null)}
}
