
import {Engine} from './engine.js';
import {box,cylinder,sphere,wedge,grid} from './geometry.js';
import {M4,clamp} from './math.js';

const DEG=Math.PI/180;
const AIRPORTS={
 NPT:{name:'Northpoint International',gate:'B06',tower:'118.700',ground:'121.800',terminalZ:-210},
 CBY:{name:'Coral Bay International',gate:'A04',tower:'119.350',ground:'121.650',terminalZ:-210},
 GMI:{name:'Supersonic Island',gate:'S12',tower:'120.900',ground:'122.100',terminalZ:-210}
};
const C={apron:[.29,.33,.35],taxi:[.23,.27,.29],runway:[.16,.18,.20],mark:[.83,.85,.82],grass:[.17,.34,.23],terminal:[.50,.58,.62],glass:[.09,.27,.36],dark:[.08,.10,.12],white:[.88,.91,.92],yellow:[.92,.62,.12],tug:[.91,.56,.08],worker:[.12,.34,.47],vest:[.95,.72,.10],wheel:[.035,.04,.045],red:[.65,.08,.07],blue:[.08,.24,.55]};
function mesh(engine,geo,color){return engine.makeMesh(...geo)}
function addPart(engine,geo,color,get){const m=mesh(engine,geo,color);return engine.add(m,color,get)}
function v2len(x,z){return Math.hypot(x,z)}
function angleWrap(a){while(a>Math.PI)a-=Math.PI*2;while(a<-Math.PI)a+=Math.PI*2;return a}
function fwd(h){return [Math.sin(h),Math.cos(h)]}
function right(h){return [Math.cos(h),-Math.sin(h)]}
function pointAhead(p,h,d){const f=fwd(h);return [p.x+f[0]*d,p.z+f[1]*d]}

class GroundCrewGame{
 constructor(root,opts={}){this.root=root;this.airport=AIRPORTS[opts.airport]||AIRPORTS.NPT;this.opts=opts;this.keys={};this.last=performance.now();this.running=true;this.mode='walk';this.job='await';this.jobClock=0;this.prompt='';this.message='Awaiting Ground assignment…';this.cameraYaw=Math.PI;this.cameraPitch=-.18;this.camDist=10;this.mouseDown=false;this.worker={x:38,z:42,h:Math.PI,y:1.05};this.tug={x:62,z:12,h:Math.PI,speed:0,steer:0,wheelbase:3.2};this.plane={x:0,z:-92,h:Math.PI,speed:0,wheelbase:20,towAngle:0,state:'parked',taxiT:0};this.hitchPrev=null;this.release={x:0,z:65};this.airborne=[{x:-380,z:450,h:.5,y:95,t:0},{x:520,z:700,h:-2.2,y:130,t:8}];this.init()}
 init(){this.buildUI();const canvas=this.root.querySelector('#gcCanvas');this.engine=new Engine(canvas);this.buildWorld();this.bind();requestAnimationFrame(t=>this.frame(t))}
 buildUI(){this.root.innerHTML=`<canvas id="gcCanvas"></canvas><div class="gc-hud"><div class="gc-top"><div class="gc-brand"><div class="gc-brand-mark">GC</div><div><b>SKYBOUND GROUND</b><small>${this.airport.name.toUpperCase()}</small></div></div><button class="gc-menu" id="gcMenuBtn">MENU</button></div><div class="gc-radio">GROUND <b>${this.airport.ground}</b> · TOWER <b>${this.airport.tower}</b></div><section class="gc-task"><div class="gc-eyebrow">GROUND OPERATIONS</div><h2 id="gcTaskTitle">Stand by for assignment</h2><p id="gcTaskText">Stay on the apron. Ground Control will assign the next aircraft requiring pushback.</p><div class="gc-task-grid"><div class="gc-chip"><small>GATE</small><b id="gcGate">—</b></div><div class="gc-chip"><small>AIRCRAFT</small><b id="gcAircraft">—</b></div></div><div class="gc-approved" id="gcApproval">AWAITING CLEARANCE</div></section><section class="gc-status"><div class="gc-eyebrow">VEHICLE STATUS</div><div class="gc-status-row"><span>MODE</span><b id="gcMode">ON FOOT</b></div><div class="gc-status-row"><span>TUG</span><b id="gcTugState">PARKED</b></div><div class="gc-status-row"><span>TOW ANGLE</span><b id="gcTow">0°</b></div><div class="gc-status-row"><span>JOB</span><b id="gcJob">STANDBY</b></div></section><div class="gc-prompt" id="gcPrompt"></div><div class="gc-help"><b>WASD</b> move / drive · <b>E</b> interact · <b>mouse drag</b> camera · <b>Shift</b> walk faster</div><div class="gc-speed"><small id="gcSpeedLabel">WALK SPEED</small><b id="gcSpeed">0</b> <span id="gcUnit">km/h</span></div><div class="gc-crosshair"></div><div class="gc-done" id="gcDone"><div class="gc-done-card"><div class="gc-eyebrow">TASK COMPLETE</div><h2>Pushback complete.</h2><p>The aircraft has been released and is taxiing under its own power.</p><button id="gcAnother">RETURN TO MENU</button></div></div></div>`;
 this.ui={title:this.root.querySelector('#gcTaskTitle'),text:this.root.querySelector('#gcTaskText'),gate:this.root.querySelector('#gcGate'),aircraft:this.root.querySelector('#gcAircraft'),approval:this.root.querySelector('#gcApproval'),mode:this.root.querySelector('#gcMode'),tug:this.root.querySelector('#gcTugState'),tow:this.root.querySelector('#gcTow'),job:this.root.querySelector('#gcJob'),prompt:this.root.querySelector('#gcPrompt'),speed:this.root.querySelector('#gcSpeed'),speedLabel:this.root.querySelector('#gcSpeedLabel'),done:this.root.querySelector('#gcDone')};
 this.root.querySelector('#gcMenuBtn').onclick=()=>location.reload();this.root.querySelector('#gcAnother').onclick=()=>location.reload();}
 buildWorld(){const e=this.engine;
 const ground=mesh(e,grid(1800,28,(x,z)=>0),C.grass);e.add(ground,C.grass,()=>M4.translation(0,-.08,0));
 addPart(e,box(520,.18,520),C.apron,()=>M4.translation(0,.02,-20));
 addPart(e,box(44,.12,1400),C.runway,()=>M4.translation(300,.08,260));
 addPart(e,box(24,.13,460),C.taxi,()=>M4.translation(120,.09,55));addPart(e,box(360,.13,24),C.taxi,()=>M4.translation(130,.09,120));
 for(let z=-420;z<900;z+=45)addPart(e,box(.6,.03,18),C.mark,()=>M4.translation(300,.16,z));
 addPart(e,box(300,26,55),C.terminal,()=>M4.translation(0,13,this.airport.terminalZ));addPart(e,box(250,10,3),C.glass,()=>M4.translation(0,17,this.airport.terminalZ+29));
 for(let x=-105;x<=105;x+=42){addPart(e,box(7,7,34),C.terminal,()=>M4.translation(x,7,this.airport.terminalZ+40));addPart(e,box(5,5,22),C.glass,()=>M4.translation(x,7,this.airport.terminalZ+55));}
 addPart(e,cylinder(9,36,24),C.terminal,()=>M4.compose([135,18,this.airport.terminalZ-8],[0,0,0],[1,1,1]));addPart(e,box(22,8,22),C.glass,()=>M4.translation(135,39,this.airport.terminalZ-8));
 // apron stand markings
 for(const x of [-84,-42,0,42,84]){addPart(e,box(.45,.025,100),C.yellow,()=>M4.translation(x,.15,-105));addPart(e,box(26,.025,.45),C.yellow,()=>M4.translation(x,.15,-62));}
 this.makeWorker();this.makeTug();this.makeAircraft(this.plane,C.white,true);for(const a of this.airborne)this.makeAircraft(a,[.75,.80,.84],false);
 // cones at release point
 for(const x of [-8,8])addPart(e,cylinder(.45,1.7,10),[.95,.35,.08],()=>M4.translation(x,.9,this.release.z));
 }
 makeWorker(){const e=this.engine,w=this.worker;addPart(e,cylinder(.36,1.1,12),C.worker,()=>M4.compose([w.x,w.y,w.z],[0,w.h,0]));addPart(e,sphere(.34,.38,.34,8,12),[.76,.58,.44],()=>M4.translation(w.x,w.y+1.0,w.z));addPart(e,box(.82,.32,.5),C.vest,()=>M4.compose([w.x,w.y+.25,w.z],[0,w.h,0]));}
 makeTug(){const e=this.engine,t=this.tug;addPart(e,box(3.8,1.35,5.9),C.tug,()=>M4.compose([t.x,1.0,t.z],[0,t.h,0]));addPart(e,box(3.2,1.25,2.3),[.28,.34,.36],()=>{const p=pointAhead(t,t.h,-1.15);return M4.compose([p[0],2.0,p[1]],[0,t.h,0])});for(const s of [-1,1])for(const q of [-1.6,1.65])addPart(e,cylinder(.48,.34,12),C.wheel,()=>{const f=fwd(t.h),r=right(t.h);const x=t.x+r[0]*s*1.72+f[0]*q,z=t.z+r[1]*s*1.72+f[1]*q;return M4.compose([x,.52,z],[Math.PI/2,t.h,0])});}
 makeAircraft(a,color,task){const e=this.engine;const scale=task?1:0.82;const bodyColor=color;addPart(e,cylinder(2.1*scale,29*scale,24),bodyColor,()=>M4.compose([a.x,a.y??2.4,a.z],[Math.PI/2,a.h,0]));addPart(e,sphere(2.1*scale,2.0*scale,4.5*scale,10,18),bodyColor,()=>{const p=pointAhead(a,a.h,16*scale);return M4.compose([p[0],a.y??2.4,p[1]],[0,a.h,0])});addPart(e,wedge([[-15*scale,1*scale],[0,-3*scale],[15*scale,1*scale],[0,6*scale]],.6*scale),bodyColor,()=>M4.compose([a.x,(a.y??2.4)+.2,a.z+1],[0,a.h,0]));addPart(e,wedge([[-6*scale,0],[0,-3*scale],[6*scale,0],[0,4*scale]],.45*scale),bodyColor,()=>{const p=pointAhead(a,a.h,-11*scale);return M4.compose([p[0],(a.y??2.4)+.4,p[1]],[0,a.h,0])});addPart(e,wedge([[-.3*scale,-3*scale],[0,0],[.3*scale,-3*scale],[0,3.5*scale]],4*scale),C.blue,()=>{const p=pointAhead(a,a.h,-12*scale);return M4.compose([p[0],(a.y??2.4)+4*scale,p[1]],[0,a.h,0])});
 if(task){for(const side of [-1,1]){addPart(e,cylinder(.55,.38,12),C.wheel,()=>{const p=pointAhead(a,a.h,-2);const r=right(a.h);return M4.compose([p[0]+r[0]*side*2.3,.58,p[1]+r[1]*side*2.3],[Math.PI/2,a.h,0])});addPart(e,cylinder(.42,.3,12),C.wheel,()=>{const p=pointAhead(a,a.h,20);const r=right(a.h);return M4.compose([p[0]+r[0]*side*.38,.46,p[1]+r[1]*side*.38],[Math.PI/2,a.h,0])});}}
 }
 bind(){window.addEventListener('keydown',e=>{if(['INPUT','TEXTAREA','SELECT'].includes(e.target?.tagName))return;this.keys[e.code]=true;if(e.code==='KeyE'&&!e.repeat)this.interact();});window.addEventListener('keyup',e=>this.keys[e.code]=false);this.root.addEventListener('pointerdown',e=>{if(e.target.closest('button'))return;this.mouseDown=true;this.px=e.clientX;this.py=e.clientY});window.addEventListener('pointerup',()=>this.mouseDown=false);window.addEventListener('pointermove',e=>{if(!this.mouseDown)return;const dx=e.clientX-this.px,dy=e.clientY-this.py;this.px=e.clientX;this.py=e.clientY;this.cameraYaw-=dx*.004;this.cameraPitch=clamp(this.cameraPitch-dy*.003,-.75,.2)});this.root.addEventListener('wheel',e=>{this.camDist=clamp(this.camDist+Math.sign(e.deltaY)*1.2,5,20)},{passive:true});}
 interact(){if(this.job==='await')return;if(this.mode==='walk'){const d=v2len(this.worker.x-this.tug.x,this.worker.z-this.tug.z);if(d<6){this.mode='tug';this.message='Tug controls active. Drive to the assigned gate.';return}}
 if(this.mode==='tug'&&!this.attached){const nose=this.nose();const d=v2len(this.tug.x-nose[0],this.tug.z-nose[1]);if(d<8&&Math.abs(this.tug.speed)<1.2&&this.job==='approved'){this.connect();return}if(d>10&&Math.abs(this.tug.speed)<.35){this.mode='walk';const r=right(this.tug.h);this.worker.x=this.tug.x+r[0]*3.2;this.worker.z=this.tug.z+r[1]*3.2;this.worker.h=this.tug.h;return}}
 if(this.mode==='tug'&&this.attached&&this.job==='release'){if(Math.abs(this.plane.towAngle)<12*DEG&&Math.abs(this.tug.speed)<.7){this.disconnect();return}}
 }
 connect(){this.attached=true;this.job='pushback';this.plane.state='tow';this.message='Connected. Reverse slowly and steer the tug. Tail swing is opposite the nose movement.';const nose=this.nose();this.tug.h=this.plane.h;const f=fwd(this.tug.h);this.tug.x=nose[0]-f[0]*2.65;this.tug.z=nose[1]-f[1]*2.65;this.hitchPrev=this.hitch();}
 disconnect(){this.attached=false;this.job='complete';this.plane.state='taxi';this.plane.taxiT=0;this.message='Pushback complete. Aircraft released to Ground.';this.ui.done.classList.add('show')}
 nose(){const f=fwd(this.plane.h);return [this.plane.x+f[0]*this.plane.wheelbase,this.plane.z+f[1]*this.plane.wheelbase]}
 hitch(){const f=fwd(this.tug.h);return [this.tug.x+f[0]*2.65,this.tug.z+f[1]*2.65]}
 update(dt){this.jobClock+=dt;if(this.job==='await'&&this.jobClock>3.5){this.job='approved';this.message=`Ground: Tug 21, pushback approved for Skybound 482 at Gate ${this.airport.gate}.`;}
 if(this.mode==='walk')this.updateWalk(dt);else this.updateTug(dt);if(this.attached)this.updateTow(dt);this.updateNPC(dt);this.updateCamera(dt);this.updateUI();}
 updateWalk(dt){let dx=(this.keys.KeyD?1:0)-(this.keys.KeyA?1:0),dz=(this.keys.KeyS?1:0)-(this.keys.KeyW?1:0);const l=Math.hypot(dx,dz);if(l){dx/=l;dz/=l;const sp=(this.keys.ShiftLeft||this.keys.ShiftRight)?8:4.5;const sy=Math.sin(this.cameraYaw),cy=Math.cos(this.cameraYaw);const wx=dx*cy+dz*sy,wz=-dx*sy+dz*cy;this.worker.x+=wx*sp*dt;this.worker.z+=wz*sp*dt;this.worker.h=Math.atan2(wx,wz)}}
 updateTug(dt){const throttle=(this.keys.KeyW?1:0)-(this.keys.KeyS?1:0);const steer=(this.keys.KeyD?1:0)-(this.keys.KeyA?1:0);const maxF=this.attached?4.3:9,maxR=this.attached?-5.2:-6;const target=throttle>0?maxF:throttle<0?maxR:0;const accel=throttle?5.8:7.5;this.tug.speed+=clamp(target-this.tug.speed,-accel*dt,accel*dt);this.tug.steer+=(steer*.52-this.tug.steer)*Math.min(1,dt*5.5);if(!throttle)this.tug.speed*=Math.max(0,1-dt*1.8);const maxSteer=this.attached?.42:.55;this.tug.steer=clamp(this.tug.steer,-maxSteer,maxSteer);this.tug.h=angleWrap(this.tug.h+(this.tug.speed/this.tug.wheelbase)*Math.tan(this.tug.steer)*dt);const f=fwd(this.tug.h);this.tug.x+=f[0]*this.tug.speed*dt;this.tug.z+=f[1]*this.tug.speed*dt;}
 updateTow(dt){const h=this.hitch();if(!this.hitchPrev)this.hitchPrev=h;const dx=h[0]-this.hitchPrev[0],dz=h[1]-this.hitchPrev[1];const f=fwd(this.plane.h),r=right(this.plane.h);const lateral=dx*r[0]+dz*r[1];const yaw=clamp(lateral/this.plane.wheelbase,-.055,.055);this.plane.h=angleWrap(this.plane.h+yaw);const nf=fwd(this.plane.h);this.plane.x=h[0]-nf[0]*this.plane.wheelbase;this.plane.z=h[1]-nf[1]*this.plane.wheelbase;this.plane.towAngle=angleWrap(this.tug.h-this.plane.h);this.hitchPrev=h;
 const deg=Math.abs(this.plane.towAngle)/DEG;if(deg>48){this.tug.speed*=Math.max(0,1-dt*6);this.message='TOW ANGLE TOO HIGH — straighten the tug before continuing.'}
 if(this.job==='pushback'&&this.plane.z>45){this.job='release';this.message='Release point reached. Straighten the tug and aircraft, stop, then press E to disconnect.';}
 }
 updateNPC(dt){for(const a of this.airborne){a.t+=dt;const rad=650+Math.sin(a.t*.08)*80;a.h+=dt*.055;a.x=Math.sin(a.h)*rad;a.z=420+Math.cos(a.h)*rad;a.y=105+Math.sin(a.t*.4)*8}if(this.plane.state==='taxi'){this.plane.taxiT+=dt;const t=this.plane.taxiT;if(t<7){this.plane.h+=(0-this.plane.h)*Math.min(1,dt*.5);this.plane.z+=7*dt}else if(t<17){this.plane.x+=12*dt;this.plane.h=Math.PI/2}else{this.plane.z+=18*dt;this.plane.h=0}}}
 updateCamera(){const target=this.mode==='walk'?this.worker:this.tug;const h=this.cameraYaw,p=this.cameraPitch,d=this.mode==='walk'?this.camDist:this.camDist+3;const cp=Math.cos(p);this.engine.target=[target.x,1.6,target.z];this.engine.cam=[target.x+Math.sin(h)*cp*d,1.6+Math.sin(-p)*d+3,target.z+Math.cos(h)*cp*d]}
 updateUI(){if(this.job==='await'){this.ui.title.textContent='Stand by for assignment';this.ui.text.textContent='Stay on the apron. Ground Control will assign the next aircraft requiring pushback.';this.ui.gate.textContent='—';this.ui.aircraft.textContent='—';this.ui.approval.textContent='AWAITING CLEARANCE'}else{this.ui.title.textContent=this.job==='complete'?'Aircraft released':this.job==='release'?'Prepare to disconnect':'Pushback · Skybound 482';this.ui.text.textContent=this.message;this.ui.gate.textContent=this.airport.gate;this.ui.aircraft.textContent='JX–200';this.ui.approval.textContent='GROUND APPROVED · PUSHBACK AUTHORIZED'}this.ui.mode.textContent=this.mode==='walk'?'ON FOOT':'TUG 21';this.ui.tug.textContent=this.attached?'CONNECTED':this.mode==='tug'?'DRIVING':'PARKED';const td=Math.abs(this.plane.towAngle/DEG);this.ui.tow.textContent=`${td.toFixed(0)}°`;this.ui.tow.className=td>42?'gc-tow-bad':td>30?'gc-tow-warn':'';this.ui.job.textContent=this.job.toUpperCase();const speed=this.mode==='walk'?v2len((this.keys.KeyD?1:0)-(this.keys.KeyA?1:0),(this.keys.KeyS?1:0)-(this.keys.KeyW?1:0))*4.5:Math.abs(this.tug.speed)*3.6;this.ui.speed.textContent=speed.toFixed(0);this.ui.speedLabel.textContent=this.mode==='walk'?'WALK SPEED':'TUG SPEED';let prompt='';if(this.job!=='await'&&this.mode==='walk'&&v2len(this.worker.x-this.tug.x,this.worker.z-this.tug.z)<6)prompt='ENTER PUSHBACK TUG';if(this.mode==='tug'&&!this.attached&&this.job==='approved'){const n=this.nose();if(v2len(this.tug.x-n[0],this.tug.z-n[1])<8)prompt='CONNECT TO NOSE GEAR'}if(this.mode==='tug'&&!this.attached&&Math.abs(this.tug.speed)<.35&&!prompt)prompt='EXIT TUG';if(this.attached&&this.job==='release'&&Math.abs(this.plane.towAngle)<12*DEG&&Math.abs(this.tug.speed)<.7)prompt='DISCONNECT · PUSHBACK COMPLETE';this.ui.prompt.innerHTML=prompt?`<kbd>E</kbd>${prompt}`:'';this.ui.prompt.classList.toggle('show',!!prompt)}
 frame(t){if(!this.running)return;const dt=Math.min(.033,(t-this.last)/1000||.016);this.last=t;this.update(dt);this.engine.render(t/1000);requestAnimationFrame(n=>this.frame(n))}
 destroy(){this.running=false;this.root.remove()}
}
export function startGroundCrew(options={}){document.body.classList.add('gc-mode');let root=document.getElementById('gcRoot');if(root)root.remove();root=document.createElement('div');root.id='gcRoot';document.body.appendChild(root);return new GroundCrewGame(root,options)}
window.SkyboundGroundCrew={start:startGroundCrew};
