const DEG=Math.PI/180,clamp=(v,a,b)=>Math.max(a,Math.min(b,v)),dist=(a,b,c,d)=>Math.hypot(a-c,b-d),wrap=a=>{while(a>Math.PI)a-=Math.PI*2;while(a<-Math.PI)a+=Math.PI*2;return a};
const vehicleForward=h=>[Math.sin(h),-Math.cos(h)],vehicleRight=h=>[Math.cos(h),Math.sin(h)];
const cameraForward=yaw=>[Math.cos(yaw),-Math.sin(yaw)],cameraRight=yaw=>[Math.sin(yaw),Math.cos(yaw)];
const headingFromForward=(x,z)=>Math.atan2(x,-z);
const AIRPORTS={NPT:{rotation:0,scale:.88},CBY:{rotation:Math.PI/3,scale:.86},GMI:{rotation:-Math.PI/5,scale:1.58}};
const BASE_GATE={id:'B06',x:1350,z:120,heading:0};
const GATES=[
 ...Array.from({length:12},(_,i)=>({id:`B${String(i+1).padStart(2,'0')}`,x:750+i*120,z:120,heading:0})),
 ...Array.from({length:8},(_,i)=>({id:`C${String(i+1).padStart(2,'0')}`,x:820+i*145,z:-250,heading:0})),
 ...Array.from({length:5},(_,i)=>({id:`A${String(i+1).padStart(2,'0')}`,x:900+i*170,z:455,heading:0}))
];

class GroundCrew{
constructor(opts={}){
  this.opts=opts;this.keys={};this.running=true;this.last=performance.now();this.scale=AIRPORTS[opts.airport]?.scale||1;
  this.role='combined';this.job='marshal-call';this.jobT=0;this.attached=false;this.mainGear=null;this.taxiPath=[];this.taxiIndex=0;this.taxiT=0;
  this.bridgeJob='bridge-idle';this.bridgeDockT=0;this.turnaroundT=0;this.downLatch=false;this.stopLatch=0;this.collisionReset=0;this.credits=5000;
  this.activeGate=BASE_GATE;this.targetGate=BASE_GATE;this.served=0;
  this.state=window.__sbGCState={ready:false,role:'combined',mode:'walk',x:0,z:0,h:0,tugX:0,tugZ:0,tugH:0,tugSpeed:0,tugSteer:0,planeX:0,planeZ:0,planeH:0,planeSpeed:0,towAngle:0,extraPlanes:[],bridgeBaseX:0,bridgeBaseZ:0,bridgeBaseH:0,bridgeH:0,bridgeExtend:7.6,bridgeHeight:3.5,bridgeDocked:false,bridgeControl:false,bridgeVisible:true,marshallingActive:false,armRaise:0,marshallSignal:'neutral',credits:this.credits};
  this.uiBuild();this.bind();window.addEventListener('skybound-ground-ready',()=>this.ready(),{once:true});requestAnimationFrame(t=>this.frame(t));
}
uiBuild(){
  const n=document.createElement('div');n.id='gcOverlay';n.innerHTML=`
  <div class="gc-brand"><b>SKYBOUND GROUND</b><span>${this.opts.airport||'NPT'} · LIVE APRON</span></div>
  <section class="gc-task"><small>GROUND OPERATIONS</small><h2 id="gcTitle">Stand by for assignment</h2><p id="gcText">Ground will assign your next task.</p><div class="gc-row"><span>GATE <b id="gcGate">B06</b></span><span>CREDITS <b id="gcCredits">5,000</b></span><span>STATUS <b id="gcStatus">SHIFT</b></span></div><div id="gcApproval" class="gc-approval">SHIFT ACTIVE</div></section>
  <div class="gc-help" id="gcHelp">WASD move · E interact · mouse drag camera</div>
  <div id="gcPrompt" class="gc-prompt"></div>
  <div id="gcCreditPop" class="gc-credit-pop"></div>
  <div class="gc-top-actions"><button id="gcAtcBtn">ATC</button><button id="gcMenu">MENU</button></div>
  <section id="gcAtcPanel" class="gc-atc-panel" aria-label="Ground ATC"><header><div><small>GROUND CONTROL</small><b>${this.opts.airport||'NPT'} GROUND</b></div><button id="gcAtcClose" aria-label="Close ATC">×</button></header><div id="gcAtcLog" class="gc-atc-log"></div><div class="gc-atc-quick"><button data-atc="request">REQUEST PUSHBACK</button><button data-atc="ready">REPORT READY</button><button data-atc="sayagain">SAY AGAIN</button></div><form id="gcAtcForm"><input id="gcAtcInput" autocomplete="off" placeholder="Type to Ground…"/><button>SEND</button></form></section>`;
  document.body.appendChild(n);
  this.ui={title:n.querySelector('#gcTitle'),text:n.querySelector('#gcText'),gate:n.querySelector('#gcGate'),credits:n.querySelector('#gcCredits'),status:n.querySelector('#gcStatus'),approval:n.querySelector('#gcApproval'),prompt:n.querySelector('#gcPrompt'),help:n.querySelector('#gcHelp'),creditPop:n.querySelector('#gcCreditPop'),atcPanel:n.querySelector('#gcAtcPanel'),atcLog:n.querySelector('#gcAtcLog'),atcInput:n.querySelector('#gcAtcInput')};
  n.querySelector('#gcMenu').onclick=()=>location.reload();n.querySelector('#gcAtcBtn').onclick=()=>this.ui.atcPanel.classList.add('open');n.querySelector('#gcAtcClose').onclick=()=>this.ui.atcPanel.classList.remove('open');
  n.querySelectorAll('[data-atc]').forEach(b=>b.onclick=()=>this.handleAtc(b.dataset.atc));
  n.querySelector('#gcAtcForm').onsubmit=e=>{e.preventDefault();const v=this.ui.atcInput.value.trim();if(v){this.atcSay('YOU',v);this.parseAtc(v);this.ui.atcInput.value=''}};
  this.atcSay('GROUND','Ground shift active. Pushback, jetbridge and marshalling are online. Baggage operations have been removed.');
}
atcSay(who,msg){const row=document.createElement('div');row.className='gc-atc-msg '+(who==='YOU'?'you':'ground');row.innerHTML=`<b>${who}</b><span>${msg}</span>`;this.ui.atcLog.appendChild(row);this.ui.atcLog.scrollTop=this.ui.atcLog.scrollHeight}
credit(delta,reason){this.credits=Math.max(0,this.credits+Math.round(delta));this.state.credits=this.credits;this.ui.credits.textContent=this.credits.toLocaleString('en-GB');const sign=delta>=0?'+':'';this.ui.creditPop.textContent=`${sign}${Math.round(delta)} · ${reason}`;this.ui.creditPop.className='gc-credit-pop show '+(delta>=0?'gain':'loss');clearTimeout(this.creditTimer);this.creditTimer=setTimeout(()=>this.ui.creditPop.classList.remove('show'),2200)}
handleAtc(type){if(type==='request'){this.atcSay('YOU',`Ground, request pushback Gate ${this.activeGate.id}.`);this.approvePushback()}else if(type==='ready'){this.atcSay('YOU',`Ground, crew ready Gate ${this.activeGate.id}.`);this.repeatAtc()}else{this.atcSay('YOU','Ground, say again.');this.repeatAtc()}}
parseAtc(v){const q=v.toLowerCase();if(q.includes('push')||q.includes('clear'))return this.approvePushback();if(q.includes('marshal')||q.includes('arrival'))return this.atcSay('GROUND',this.marshallingInstruction());if(q.includes('bridge'))return this.atcSay('GROUND',this.state.bridgeDocked?'Jetbridge is connected. Disconnect and retract it before pushback.':'Jetbridge is available at the terminal-side pedestal.');if(q.includes('credit'))return this.atcSay('GROUND',`Current Sky Credits: ${this.credits.toLocaleString('en-GB')}.`);this.repeatAtc()}
marshallingInstruction(){return this.job.startsWith('marshal')?`Inbound JX-200 for Gate ${this.activeGate.id}. Take the marshalling position. Arrow keys command the aircraft. Hold Space to raise your wands; release to lower them. When fully raised, press Down for the crossed-wand stop.`:`No active marshalling arrival. Current task: ${this.jobLabel()}.`}
jobLabel(){if(this.job.startsWith('marshal'))return'MARSHALLING';if(this.job==='parked'||this.job==='bridge-service')return'JETBRIDGE';if(['await','approved','pushback','release'].includes(this.job))return'PUSHBACK';if(this.job==='complete')return'TAXI OUT';return'STAND BY'}
repeatAtc(){let msg=this.marshallingInstruction();if(this.job==='parked')msg=`Aircraft parked Gate ${this.activeGate.id}. Connect the jetbridge.`;else if(this.job==='bridge-service')msg=`Turnaround complete Gate ${this.activeGate.id}. Disconnect and retract the jetbridge, then request pushback.`;else if(this.job==='await')msg=`Gate ${this.activeGate.id} is clear for departure servicing. Request pushback when the bridge is retracted.`;else if(this.job==='approved')msg=`Pushback approved Gate ${this.activeGate.id}. Connect the tug at the nose gear.`;else if(this.job==='pushback')msg=`Continue pushback Gate ${this.activeGate.id}.`;else if(this.job==='release')msg='Release point reached. Stop and disconnect.';this.atcSay('GROUND',msg)}
approvePushback(){if(this.job==='await'&&!this.state.bridgeDocked){this.job='approved';this.atcSay('GROUND',`Pushback approved Gate ${this.activeGate.id}. Proceed to the nose gear.`)}else if(this.state.bridgeDocked)this.atcSay('GROUND','Negative pushback. Jetbridge is still connected.');else this.repeatAtc()}
bind(){const block=['KeyW','KeyA','KeyS','KeyD','KeyE','Space','ShiftLeft','ShiftRight','ArrowUp','ArrowDown','ArrowLeft','ArrowRight','KeyQ','KeyR','KeyF'];this.kd=e=>{if(!window.__skyboundGroundMode)return;if(['INPUT','TEXTAREA','SELECT'].includes(e.target?.tagName))return;if(block.includes(e.code)){e.preventDefault();e.stopImmediatePropagation()}this.keys[e.code]=true;if(e.code==='KeyE'&&!e.repeat)this.interact();if(e.code==='ArrowDown'&&!e.repeat&&this.state.marshallingActive)this.tryStopSignal()};this.ku=e=>{if(!window.__skyboundGroundMode)return;this.keys[e.code]=false;if(block.includes(e.code)){e.preventDefault();e.stopImmediatePropagation()}};window.addEventListener('keydown',this.kd,true);window.addEventListener('keyup',this.ku,true)}
ready(){const s=this.state,ps=window.__sbPilotState;if(!ps||!Number.isFinite(ps.x)||!Number.isFinite(ps.z))return;this.baseWorld={x:ps.x,z:ps.z,h:ps.heading||0};this.targetGateWorld={x:ps.x,z:ps.z,h:ps.heading||0};s.x=ps.x+34;s.z=ps.z+18;s.h=ps.heading||0;const pf=vehicleForward(ps.heading||0);s.tugX=ps.x+pf[0]*42+18;s.tugZ=ps.z+pf[1]*42+12;s.tugH=(ps.heading||0)+Math.PI;this.activeGate=BASE_GATE;this.buildBusyAirport();this.setupPermanentBridge();this.spawnArrival();this.ui.gate.textContent='B06';this.ui.help.textContent='Walk: WASD · E interact · Marshalling: arrows + hold Space · Tug: W/S/A/D + Space brake · Bridge: W/S/A/D + R/F';this.atcSay('GROUND',`Inbound JX-200 assigned Gate B06. Proceed to the marshalling position and guide it onto stand.`)}
worldFromGate(g){const dx=(g.x-BASE_GATE.x)*this.scale,dz=(g.z-BASE_GATE.z)*this.scale,r=vehicleRight(this.baseWorld.h),f=vehicleForward(this.baseWorld.h);return{x:this.baseWorld.x+r[0]*dx+f[0]*(-dz),z:this.baseWorld.z+r[1]*dx+f[1]*(-dz),h:wrap(this.baseWorld.h+g.heading)}}
localPoint(x,z){const dx=(x-BASE_GATE.x)*this.scale,dz=(z-BASE_GATE.z)*this.scale,r=vehicleRight(this.baseWorld.h),f=vehicleForward(this.baseWorld.h);return{x:this.baseWorld.x+r[0]*dx+f[0]*(-dz),z:this.baseWorld.z+r[1]*dx+f[1]*(-dz)}}
buildBusyAirport(){const extras=GATES.filter(g=>g.id!==BASE_GATE.id).slice(0,24).map(g=>{const w=this.worldFromGate(g);return{id:g.id,x:w.x,z:w.z,h:w.h,visible:true}});this.state.extraPlanes=extras}
setupPermanentBridge(){const s=this.state,target=this.targetGateWorld,pf=vehicleForward(target.h),pr=vehicleRight(target.h);this.bridgeDoor={x:target.x+pf[0]*12.7-pr[0]*2.75,z:target.z+pf[1]*12.7-pr[1]*2.75,y:4.25};s.bridgeBaseX=this.bridgeDoor.x-pr[0]*17-pf[0]*2.5;s.bridgeBaseZ=this.bridgeDoor.z-pr[1]*17-pf[1]*2.5;s.bridgeBaseH=headingFromForward(this.bridgeDoor.x-s.bridgeBaseX,this.bridgeDoor.z-s.bridgeBaseZ);s.bridgeH=s.bridgeBaseH;s.bridgeExtend=7.5;s.bridgeHeight=3.45;s.bridgeDocked=false;s.bridgeControl=false;s.bridgeVisible=true;this.bridgeControlPoint={x:s.bridgeBaseX+pr[0]*2.3,z:s.bridgeBaseZ+pr[1]*2.3}}
bridgeHead(){const s=this.state,f=vehicleForward(s.bridgeH);return{x:s.bridgeBaseX+f[0]*s.bridgeExtend,z:s.bridgeBaseZ+f[1]*s.bridgeExtend,y:s.bridgeHeight}}
bridgeMetrics(){const s=this.state,h=this.bridgeHead(),d=this.bridgeDoor,dx=d.x-h.x,dz=d.z-h.z,targetH=headingFromForward(d.x-s.bridgeBaseX,d.z-s.bridgeBaseZ);return{dist:Math.hypot(dx,dz,d.y-h.y),angle:Math.abs(wrap(targetH-s.bridgeH)),height:Math.abs(d.y-h.y),targetH,targetExtend:clamp(Math.hypot(d.x-s.bridgeBaseX,d.z-s.bridgeBaseZ),6.5,24),targetHeight:d.y}}
spawnArrival(){const s=this.state,start=this.localPoint(BASE_GATE.x,650),marshal=this.localPoint(BASE_GATE.x,62);s.planeX=start.x;s.planeZ=start.z;s.planeH=this.targetGateWorld.h;s.planeSpeed=0;s.marshallingActive=false;s.armRaise=0;s.marshallSignal='neutral';s.bridgeDocked=false;s.bridgeExtend=7.5;s.bridgeHeight=3.45;this.marshallingSpot={x:marshal.x,z:marshal.z};this.job='marshal-call';this.jobT=0;this.stopLatch=0;this.collisionReset=0;this.home={x:this.targetGateWorld.x,z:this.targetGateWorld.z};this.ui.approval.textContent='INBOUND AIRCRAFT'}
tryStopSignal(){const s=this.state;if(!s.marshallingActive)return;if(s.armRaise<.84){this.credit(-25,'INVALID STOP SIGNAL');this.atcSay('GROUND','Stop signal not recognised — raise the wands fully before crossing them.');return}this.stopLatch=1.25;s.marshallSignal='stop'}
interact(){const s=this.state;if(!s.ready)return;if(s.mode==='bridge')return this.bridgeInteract();if(s.mode==='walk'){
  if(this.job.startsWith('marshal')&&dist(s.x,s.z,this.marshallingSpot.x,this.marshallingSpot.z)<6){s.marshallingActive=true;s.mode='marshal';s.x=this.marshallingSpot.x;s.z=this.marshallingSpot.z;this.job='marshal-active';this.atcSay('GROUND',`Marshaller in position Gate ${this.activeGate.id}. Aircraft is awaiting your signals.`);return}
  if(this.bridgeControlPoint&&dist(s.x,s.z,this.bridgeControlPoint.x,this.bridgeControlPoint.z)<5.5&&(this.job==='parked'||this.job==='bridge-service'||s.bridgeDocked)){if(s.bridgeDocked){s.bridgeDocked=false;s.bridgeControl=true;s.mode='bridge';this.bridgeJob='bridge-retract';this.atcSay('GROUND','Jetbridge disconnected. Retract it clear of the aircraft.');}else{s.bridgeControl=true;s.mode='bridge';this.bridgeJob='bridge-control'}return}
  if(dist(s.x,s.z,s.tugX,s.tugZ)<6&&['await','approved','pushback','release'].includes(this.job)){s.mode='tug';s.tugSpeed=0;return}
}
if(s.mode==='tug'&&!this.attached){const n=this.nose();if(this.job==='approved'&&dist(s.tugX,s.tugZ,n[0],n[1])<7&&Math.abs(s.tugSpeed)<.7){this.attached=true;this.job='pushback';s.tugSpeed=0;s.tugSteer=0;s.tugH=wrap(s.planeH+Math.PI);const f=vehicleForward(s.tugH);s.tugX=n[0]-f[0]*3.45;s.tugZ=n[1]-f[1]*3.45;const pf=vehicleForward(s.planeH);this.mainGear={x:n[0]-pf[0]*32,z:n[1]-pf[1]*32};return}if(dist(s.tugX,s.tugZ,n[0],n[1])>10&&Math.abs(s.tugSpeed)<.4){s.mode='walk';const r=vehicleRight(s.tugH);s.x=s.tugX+r[0]*3;s.z=s.tugZ+r[1]*3;s.h=s.tugH;return}}
if(this.attached&&this.job==='release'&&Math.abs(s.tugSpeed)<.5){this.attached=false;this.job='complete';this.mainGear=null;this.taxiT=0;this.makeTaxiPath();this.atcSay('GROUND','Disconnect approved. Aircraft is under its own power.')}}
bridgeInteract(){const s=this.state;if(s.bridgeDocked){s.bridgeDocked=false;this.bridgeJob='bridge-retract';return}const m=this.bridgeMetrics();if((this.job==='parked'||this.job==='bridge-service')&&m.dist<3.4&&m.angle<16*DEG&&m.height<1.15){this.bridgeJob='bridge-docking';this.bridgeDockT=0;return}}
update(dt){const s=this.state;if(!s.ready)return;this.jobT+=dt;if(s.mode==='walk')this.walk(dt);else if(s.mode==='marshal')this.marshalling(dt);else if(s.mode==='bridge')this.bridgeDrive(dt);else if(s.mode==='tug')this.drive(dt);if(this.bridgeJob==='bridge-docking')this.bridgeDock(dt);if(this.attached)this.tow(dt);if(this.job==='complete')this.taxi(dt);if(this.job==='between')this.nextArrival(dt);if(this.job==='bridge-service'){this.turnaroundT+=dt;if(this.turnaroundT>5&&!this.turnaroundAnnounced){this.turnaroundAnnounced=true;this.atcSay('GROUND',`Gate ${this.activeGate.id}, turnaround complete. Disconnect and retract the jetbridge, then request pushback.`)}}if(this.job==='marshal-collision'){this.collisionReset+=dt;if(this.collisionReset>3)this.resetAfterCollision()}this.uiUpdate()}
walk(dt){const s=this.state,side=(this.keys.KeyD?1:0)-(this.keys.KeyA?1:0),fore=(this.keys.KeyW?1:0)-(this.keys.KeyS?1:0),l=Math.hypot(side,fore);if(!l)return;const cam=Number.isFinite(window.__sbGCCamYaw)?window.__sbGCCamYaw:0,cf=cameraForward(cam),cr=cameraRight(cam),dx=(cf[0]*fore+cr[0]*side)/l,dz=(cf[1]*fore+cr[1]*side)/l,sp=this.keys.ShiftLeft||this.keys.ShiftRight?8:4.5;s.x+=dx*sp*dt;s.z+=dz*sp*dt;s.h=headingFromForward(dx,dz)}
marshalling(dt){const s=this.state,toPlaneX=s.planeX-s.x,toPlaneZ=s.planeZ-s.z;if(Math.hypot(toPlaneX,toPlaneZ)>.01)s.h=headingFromForward(toPlaneX,toPlaneZ);
  if(this.keys.Space&&this.stopLatch<=0)s.armRaise=clamp(s.armRaise+dt*.62,0,1);else if(this.stopLatch<=0)s.armRaise=clamp(s.armRaise-dt*.48,0,1);
  if(this.stopLatch>0){this.stopLatch-=dt;s.marshallSignal='stop'}else if(this.keys.ArrowLeft)s.marshallSignal='left';else if(this.keys.ArrowRight)s.marshallSignal='right';else if(this.keys.ArrowUp)s.marshallSignal='forward';else s.marshallSignal='neutral';
  let turn=0,targetSpeed=null;if(s.marshallSignal==='forward')targetSpeed=3.1;else if(s.marshallSignal==='left'){targetSpeed=2.35;turn=-.20}else if(s.marshallSignal==='right'){targetSpeed=2.35;turn=.20}
  if(targetSpeed!==null){const accel=targetSpeed>s.planeSpeed?1.35:2.05;s.planeSpeed+=(targetSpeed-s.planeSpeed)*Math.min(1,dt*accel)}
  if(s.marshallSignal==='stop')s.planeSpeed=Math.max(0,s.planeSpeed-4.8*dt);
  s.planeH=wrap(s.planeH+turn*dt);const f=vehicleForward(s.planeH);s.planeX+=f[0]*s.planeSpeed*dt;s.planeZ+=f[1]*s.planeSpeed*dt;
  const tf=vehicleForward(this.targetGateWorld.h),rx=s.planeX-this.targetGateWorld.x,rz=s.planeZ-this.targetGateWorld.z,along=rx*tf[0]+rz*tf[1];
  if(along>30){s.planeSpeed=0;s.marshallSignal='neutral';s.marshallingActive=false;s.mode='walk';this.job='marshal-collision';this.collisionReset=0;this.credit(-1200,'TERMINAL COLLISION');this.atcSay('GROUND','Emergency. Aircraft collision at the stand. 1,200 credits deducted. Stand by for reset.');return}
  if(s.marshallSignal==='stop'&&s.planeSpeed<.12)this.evaluateStop();
}
evaluateStop(){const s=this.state;if(this.stopEvaluated)return;this.stopEvaluated=true;setTimeout(()=>this.stopEvaluated=false,900);const posErr=dist(s.planeX,s.planeZ,this.targetGateWorld.x,this.targetGateWorld.z),hdgErr=Math.abs(wrap(s.planeH-this.targetGateWorld.h))/DEG;if(posErr>25){this.credit(-150,'STOPPED TOO EARLY');this.atcSay('GROUND',`Too early — ${posErr.toFixed(0)} m from the stand. Continue marshalling.`);this.stopLatch=0;s.marshallSignal='neutral';return}
  const score=Math.round(500-posErr*13-hdgErr*7);this.credit(score,score>=0?'MARSHALLING COMPLETE':'POOR PARK');s.planeSpeed=0;s.marshallingActive=false;s.mode='walk';s.marshallSignal='neutral';s.armRaise=0;this.job='parked';this.turnaroundT=0;this.turnaroundAnnounced=false;this.atcSay('GROUND',`Marshalling complete Gate ${this.activeGate.id}. Stop error ${posErr.toFixed(1)} m, heading error ${hdgErr.toFixed(1)}°. ${score>=0?`Award ${score} credits.`:`Penalty ${Math.abs(score)} credits.`} Connect the jetbridge.`)}
resetAfterCollision(){this.spawnArrival();this.atcSay('GROUND','Replacement inbound aircraft established. Return to the marshalling position.')}
bridgeDrive(dt){const s=this.state;if(s.bridgeDocked)return;const rot=(this.keys.KeyD?1:0)-(this.keys.KeyA?1:0),ext=(this.keys.KeyW?1:0)-(this.keys.KeyS?1:0),vert=(this.keys.KeyR?1:0)-(this.keys.KeyF?1:0);s.bridgeH=wrap(s.bridgeH+rot*.34*dt);s.bridgeExtend=clamp(s.bridgeExtend+ext*5.2*dt,6.2,24);s.bridgeHeight=clamp(s.bridgeHeight+vert*2.1*dt,2.8,6.0);if(this.bridgeJob==='bridge-retract'&&s.bridgeExtend<8.5){s.mode='walk';s.bridgeControl=false;this.bridgeJob='bridge-clear';if(this.job==='bridge-service'){this.job='await';this.atcSay('GROUND',`Jetbridge clear Gate ${this.activeGate.id}. Aircraft ready for pushback request.`)}}if(this.keys.KeyQ){this.keys.KeyQ=false;s.mode='walk';s.bridgeControl=false}}
bridgeDock(dt){const s=this.state,m=this.bridgeMetrics();this.bridgeDockT+=dt;const k=Math.min(1,dt*4.2);s.bridgeH=wrap(s.bridgeH+wrap(m.targetH-s.bridgeH)*k);s.bridgeExtend+=(m.targetExtend-s.bridgeExtend)*k;s.bridgeHeight+=(m.targetHeight-s.bridgeHeight)*k;if(this.bridgeDockT>1.2||this.bridgeMetrics().dist<.22){s.bridgeDocked=true;s.bridgeControl=false;s.mode='walk';this.bridgeJob='bridge-complete';this.job='bridge-service';this.turnaroundT=0;this.turnaroundAnnounced=false;this.credit(120,'JETBRIDGE CONNECTED');this.atcSay('GROUND',`Jetbridge docked Gate ${this.activeGate.id}. Turnaround in progress.`)}}
drive(dt){const s=this.state,gas=this.keys.KeyW?1:0,brake=this.keys.KeyS?1:0,hard=this.keys.Space?1:0,steer=(this.keys.KeyD?1:0)-(this.keys.KeyA?1:0),forwardMax=this.attached?4.6:9,reverseMax=this.attached?-3.7:-6;if(hard){const dec=17*dt;s.tugSpeed=Math.abs(s.tugSpeed)<=dec?0:s.tugSpeed-Math.sign(s.tugSpeed)*dec}else if(gas){if(s.tugSpeed<-.12)s.tugSpeed=Math.min(0,s.tugSpeed+11*dt);else s.tugSpeed=Math.min(forwardMax,s.tugSpeed+5.2*dt)}else if(brake){if(s.tugSpeed>.12)s.tugSpeed=Math.max(0,s.tugSpeed-11*dt);else s.tugSpeed=Math.max(reverseMax,s.tugSpeed-4*dt)}else{s.tugSpeed*=Math.max(0,1-dt*2.2);if(Math.abs(s.tugSpeed)<.025)s.tugSpeed=0}const target=steer*.55;s.tugSteer+=(target-s.tugSteer)*Math.min(1,dt*4);if(!steer)s.tugSteer*=Math.max(0,1-dt*4.2);s.tugH=wrap(s.tugH+(s.tugSpeed/4.7)*Math.tan(s.tugSteer)*dt);const f=vehicleForward(s.tugH);s.tugX+=f[0]*s.tugSpeed*dt;s.tugZ+=f[1]*s.tugSpeed*dt}
nose(){const s=this.state,f=vehicleForward(s.planeH);return[s.planeX+f[0]*18.5,s.planeZ+f[1]*18.5]}
hitch(){const s=this.state,f=vehicleForward(s.tugH);return[s.tugX+f[0]*3.45,s.tugZ+f[1]*3.45]}
tow(dt){const s=this.state,h=this.hitch(),wheelbase=32,noseOffset=18.5;if(!this.mainGear){const pf=vehicleForward(s.planeH);this.mainGear={x:h[0]-pf[0]*wheelbase,z:h[1]-pf[1]*wheelbase}}const vx=h[0]-this.mainGear.x,vz=h[1]-this.mainGear.z,vl=Math.hypot(vx,vz);if(vl<.001)return;const targetH=headingFromForward(vx/vl,vz/vl),dh=wrap(targetH-s.planeH),maxStep=(.35+Math.abs(s.tugSpeed)*.12)*dt;s.planeH=wrap(s.planeH+clamp(dh,-maxStep,maxStep));const pf=vehicleForward(s.planeH);this.mainGear.x=h[0]-pf[0]*wheelbase;this.mainGear.z=h[1]-pf[1]*wheelbase;s.planeX=h[0]-pf[0]*noseOffset;s.planeZ=h[1]-pf[1]*noseOffset;s.towAngle=wrap(s.tugH-(s.planeH+Math.PI));if(this.job==='pushback'&&dist(s.planeX,s.planeZ,this.home.x,this.home.z)>48){this.job='release';this.atcSay('GROUND','Release point reached. Stop the tug and disconnect.')}}
makeTaxiPath(){const route=[{x:1350,z:300},{x:600,z:300},{x:460,z:300},{x:460,z:1800},{x:110,z:1800}].map(p=>this.localPoint(p.x,p.z));this.taxiPath=[{x:this.state.planeX,z:this.state.planeZ},...route];this.taxiIndex=1}
taxi(dt){const s=this.state;this.taxiT+=dt;s.towAngle=0;if(this.taxiT<2)return;if(this.taxiIndex>=this.taxiPath.length){this.job='between';this.jobT=0;this.served++;this.credit(180,'SAFE PUSHBACK');this.atcSay('GROUND','Aircraft clear. Another inbound is approaching Gate B06.');return}const w=this.taxiPath[this.taxiIndex],dx=w.x-s.planeX,dz=w.z-s.planeZ,d=Math.hypot(dx,dz);if(d<8){this.taxiIndex++;return}const target=headingFromForward(dx/d,dz/d),dh=wrap(target-s.planeH);s.planeH=wrap(s.planeH+clamp(dh,-.55*dt,.55*dt));const f=vehicleForward(s.planeH),spd=Math.abs(dh)>.45?5.5:10.5;s.planeX+=f[0]*spd*dt;s.planeZ+=f[1]*spd*dt}
nextArrival(dt){if(this.jobT<3.5)return;this.spawnArrival();this.atcSay('GROUND',`New arrival for Gate B06. Marshaller required.`)}
uiUpdate(){const s=this.state,p=[];this.ui.gate.textContent=this.activeGate.id;this.ui.credits.textContent=this.credits.toLocaleString('en-GB');this.ui.status.textContent=this.jobLabel();
if(this.job==='marshal-call'){this.ui.title.textContent='Inbound aircraft · Gate B06';this.ui.text.textContent='Walk to the marshalling position in front of the stand and press E.';this.ui.approval.textContent='MARSHALLER REQUIRED';if(dist(s.x,s.z,this.marshallingSpot.x,this.marshallingSpot.z)<6)p.push('E · START MARSHALLING')}
else if(this.job==='marshal-active'){this.ui.title.textContent='Marshal the aircraft';this.ui.text.textContent=`↑ straight · ←/→ steer · Release arrows = aircraft keeps rolling · Hold SPACE to raise wands (${Math.round(s.armRaise*100)}%) · release Space to lower · ↓ crossed-wand STOP when fully raised.`;this.ui.approval.textContent=s.armRaise>.84?'STOP SIGNAL ARMED':'GUIDE AIRCRAFT'}
else if(this.job==='marshal-collision'){this.ui.title.textContent='Aircraft collision';this.ui.text.textContent='No safety stop was applied. Credits were deducted. Replacement aircraft incoming.';this.ui.approval.textContent='INCIDENT'}
else if(this.job==='parked'){this.ui.title.textContent='Aircraft parked';this.ui.text.textContent='Marshalling complete. Walk to the jetbridge controls and connect the bridge.';this.ui.approval.textContent='CONNECT JETBRIDGE'}
else if(this.job==='bridge-service'){this.ui.title.textContent='Turnaround at Gate B06';this.ui.text.textContent=this.turnaroundAnnounced?'Boarding complete. Disconnect and retract the jetbridge.':'Jetbridge connected. Turnaround in progress.';this.ui.approval.textContent=this.turnaroundAnnounced?'CLEAR BRIDGE':'AT GATE'}
else if(this.job==='await'){this.ui.title.textContent='Ready for departure';this.ui.text.textContent='Jetbridge clear. Open ATC and request pushback.';this.ui.approval.textContent='REQUEST PUSHBACK'}
else if(this.job==='approved'){this.ui.title.textContent='Pushback approved';this.ui.text.textContent='Drive the tug to the nose gear and press E to connect.';this.ui.approval.textContent='PUSHBACK APPROVED'}
else if(this.job==='pushback'){this.ui.title.textContent='Pushback in progress';this.ui.text.textContent='Use the tug normally. Tow angle remains unrestricted.';this.ui.approval.textContent='TUG CONNECTED'}
else if(this.job==='release'){this.ui.title.textContent='Release point';this.ui.text.textContent='Stop the tug and press E to disconnect.';this.ui.approval.textContent='DISCONNECT'}
else if(this.job==='complete'){this.ui.title.textContent='Aircraft taxiing';this.ui.text.textContent='NPC control has taken over and is following the taxiway.';this.ui.approval.textContent='TAXI OUT'}
else{this.ui.title.textContent='Stand by';this.ui.text.textContent='Next aircraft is inbound.';this.ui.approval.textContent='HIGH DEMAND'}
if(s.mode==='walk'&&this.bridgeControlPoint&&dist(s.x,s.z,this.bridgeControlPoint.x,this.bridgeControlPoint.z)<5.5&&(this.job==='parked'||this.job==='bridge-service'||s.bridgeDocked))p.push(s.bridgeDocked?'E · DISCONNECT JETBRIDGE':'E · OPERATE JETBRIDGE');if(s.mode==='bridge'){const m=this.bridgeMetrics();if(!s.bridgeDocked&&this.job==='parked'&&m.dist<3.4&&m.angle<16*DEG&&m.height<1.15)p.push('E · DOCK JETBRIDGE');else p.push('Q · EXIT BRIDGE CONTROLS')}
if(s.mode==='walk'&&dist(s.x,s.z,s.tugX,s.tugZ)<6&&['await','approved','pushback','release'].includes(this.job))p.push('E · ENTER TUG');if(s.mode==='tug'&&!this.attached&&this.job==='approved'){const n=this.nose();if(dist(s.tugX,s.tugZ,n[0],n[1])<7)p.push('E · CONNECT TUG')}if(this.attached&&this.job==='release'&&Math.abs(s.tugSpeed)<.5)p.push('E · DISCONNECT');this.ui.prompt.textContent=p[0]||'';this.ui.prompt.classList.toggle('show',p.length>0)}
frame(t){if(!this.running)return;const dt=Math.min(.033,(t-this.last)/1000||.016);this.last=t;this.update(dt);requestAnimationFrame(n=>this.frame(n))}}
export function startGroundCrew(opts={}){document.body.classList.add('gc-same-world');return new GroundCrew(opts)}window.SkyboundGroundCrew={start:startGroundCrew};
