const DEG=Math.PI/180,clamp=(v,a,b)=>Math.max(a,Math.min(b,v)),dist=(a,b,c,d)=>Math.hypot(a-c,b-d),wrap=a=>{while(a>Math.PI)a-=Math.PI*2;while(a<-Math.PI)a+=Math.PI*2;return a};
// Three.js models face local -Z. These helpers match what the player actually sees.
const vehicleForward=h=>[Math.sin(h),-Math.cos(h)],vehicleRight=h=>[Math.cos(h),Math.sin(h)];
const cameraForward=yaw=>[Math.cos(yaw),-Math.sin(yaw)],cameraRight=yaw=>[Math.sin(yaw),Math.cos(yaw)];
const headingFromForward=(x,z)=>Math.atan2(x,-z);
const AIRPORTS={NPT:{rotation:0,scale:.88},CBY:{rotation:Math.PI/3,scale:.86},GMI:{rotation:-Math.PI/5,scale:1.58}};
const BASE_GATE={id:'B06',x:1350,z:120,heading:0};
const GATES=['B01','B02','B03','B04','B05','B06','B07','B08'].map((id,i)=>({id,x:750+i*120,z:120,heading:0}));

class GroundCrew{
constructor(opts={}){
  this.opts=opts;this.keys={};this.job='await';this.jobT=0;this.attached=false;this.running=true;this.last=performance.now();
  this.activeGate=BASE_GATE;this.scale=AIRPORTS[opts.airport]?.scale||1;this.queue=[];this.served=new Set();this.taxiPath=[];this.taxiIndex=0;this.nextJobT=0;
  this.state=window.__sbGCState={ready:false,mode:'walk',x:0,z:0,h:0,tugX:0,tugZ:0,tugH:0,tugSpeed:0,tugSteer:0,planeX:0,planeZ:0,planeH:0,towAngle:0,extraPlanes:[]};
  this.uiBuild();this.bind();window.addEventListener('skybound-ground-ready',()=>this.ready(),{once:true});requestAnimationFrame(t=>this.frame(t));
}
uiBuild(){
  let n=document.createElement('div');n.id='gcOverlay';n.innerHTML=`
  <div class="gc-brand"><b>SKYBOUND GROUND</b><span>${this.opts.airport||'NPT'} · LIVE APRON</span></div>
  <section class="gc-task"><small>GROUND OPERATIONS</small><h2 id="gcTitle">Stand by for assignment</h2><p id="gcText">Open ATC and request pushback clearance when the assigned aircraft is ready.</p><div class="gc-row"><span>GATE <b id="gcGate">—</b></span><span>AIRCRAFT <b>JX–200</b></span><span>TOW <b id="gcTow">0°</b></span></div><div id="gcApproval" class="gc-approval">AWAITING GROUND</div></section>
  <div class="gc-help">W gas · S brake/reverse · A/D steer · Space hard brake · E interact · mouse drag camera</div>
  <div id="gcPrompt" class="gc-prompt"></div>
  <div class="gc-top-actions"><button id="gcAtcBtn">ATC</button><button id="gcMenu">MENU</button></div>
  <section id="gcAtcPanel" class="gc-atc-panel" aria-label="Ground ATC"><header><div><small>GROUND CONTROL</small><b>${this.opts.airport||'NPT'} GROUND</b></div><button id="gcAtcClose" aria-label="Close ATC">×</button></header><div id="gcAtcLog" class="gc-atc-log"></div><div class="gc-atc-quick"><button data-atc="request">REQUEST PUSHBACK</button><button data-atc="ready">REPORT READY</button><button data-atc="sayagain">SAY AGAIN</button></div><form id="gcAtcForm"><input id="gcAtcInput" autocomplete="off" placeholder="Type to Ground…"/><button>SEND</button></form></section>`;
  document.body.appendChild(n);
  this.ui={title:n.querySelector('#gcTitle'),text:n.querySelector('#gcText'),gate:n.querySelector('#gcGate'),tow:n.querySelector('#gcTow'),approval:n.querySelector('#gcApproval'),prompt:n.querySelector('#gcPrompt'),atcPanel:n.querySelector('#gcAtcPanel'),atcLog:n.querySelector('#gcAtcLog'),atcInput:n.querySelector('#gcAtcInput')};
  n.querySelector('#gcMenu').onclick=()=>location.reload();
  n.querySelector('#gcAtcBtn').onclick=()=>this.ui.atcPanel.classList.add('open');
  n.querySelector('#gcAtcClose').onclick=()=>this.ui.atcPanel.classList.remove('open');
  n.querySelectorAll('[data-atc]').forEach(b=>b.onclick=()=>this.handleAtc(b.dataset.atc));
  n.querySelector('#gcAtcForm').onsubmit=e=>{e.preventDefault();let v=this.ui.atcInput.value.trim();if(v){this.atcSay('YOU',v);this.parseAtc(v);this.ui.atcInput.value=''}};
  this.atcSay('GROUND',`Ground crew shift active. ${this.activeGate.id} will be your first pushback assignment.`);
}
atcSay(who,msg){let row=document.createElement('div');row.className='gc-atc-msg '+(who==='YOU'?'you':'ground');row.innerHTML=`<b>${who}</b><span>${msg}</span>`;this.ui.atcLog.appendChild(row);this.ui.atcLog.scrollTop=this.ui.atcLog.scrollHeight}
handleAtc(type){if(type==='request'){this.atcSay('YOU',`Ground, tug requests pushback approval for Gate ${this.activeGate.id}.`);this.approvePushback()}else if(type==='ready'){this.atcSay('YOU',`Ground, tug is ready at Gate ${this.activeGate.id}.`);this.atcSay('GROUND',this.job==='approved'?'Roger. Proceed to the nose gear and connect when aligned.':this.job==='pushback'?'Continue approved pushback.':this.job==='release'?'Pushback complete. Straighten and disconnect.':'Stand by for the next assignment.')}else{this.atcSay('YOU','Ground, say again.');this.repeatAtc()}}
parseAtc(v){let q=v.toLowerCase();if(q.includes('push')||q.includes('clear')||q.includes('approve'))return this.approvePushback();if(q.includes('ready'))return this.handleAtc('ready');if(q.includes('say again')||q.includes('repeat'))return this.repeatAtc();if(q.includes('gate')||q.includes('where'))return this.atcSay('GROUND',`Your assigned departure is Gate ${this.activeGate.id}, JX-200. Drive the tug to its nose gear.`);if(q.includes('disconnect')||q.includes('release'))return this.atcSay('GROUND',this.job==='release'?'Approved to disconnect when straight and stopped.':'Negative. Complete the pushback to the marked release point first.');this.atcSay('GROUND',`Ground copies. Current task is Gate ${this.activeGate.id}. ${this.job==='await'?'Request pushback when ready.':this.job==='approved'?'Pushback is approved.':this.job==='pushback'?'Continue pushback.':this.job==='release'?'Straighten and disconnect.':'Stand by.'}`)}
approvePushback(){if(this.job==='await'){this.job='approved';this.jobT=0;this.atcSay('GROUND',`Pushback approved Gate ${this.activeGate.id}. Proceed to the nose gear, connect, then push facing away from the stand.`)}else if(this.job==='approved')this.atcSay('GROUND',`Pushback already approved for Gate ${this.activeGate.id}.`);else this.repeatAtc()}
repeatAtc(){let msg=this.job==='await'?`Gate ${this.activeGate.id}, request pushback when your tug is ready.`:this.job==='approved'?`Gate ${this.activeGate.id}, pushback approved. Connect at the nose gear.`:this.job==='pushback'?`Continue pushback. Maintain a safe tow angle.`:this.job==='release'?`Release point reached. Straighten, stop, and disconnect.`:`Job complete. Stand by for another departure.`;this.atcSay('GROUND',msg)}
bind(){let block=['KeyW','KeyA','KeyS','KeyD','KeyE','Space','ShiftLeft','ShiftRight','ArrowUp','ArrowDown','ArrowLeft','ArrowRight','KeyQ'];this.kd=e=>{if(!window.__skyboundGroundMode)return;if(['INPUT','TEXTAREA','SELECT'].includes(e.target?.tagName))return;if(block.includes(e.code)){e.preventDefault();e.stopImmediatePropagation()}this.keys[e.code]=true;if(e.code==='KeyE'&&!e.repeat)this.interact()};this.ku=e=>{if(!window.__skyboundGroundMode)return;this.keys[e.code]=false;if(block.includes(e.code)){e.preventDefault();e.stopImmediatePropagation()}};window.addEventListener('keydown',this.kd,true);window.addEventListener('keyup',this.ku,true)}
ready(){let s=this.state,ps=window.__sbPilotState;if(ps&&Number.isFinite(ps.x)&&Number.isFinite(ps.z)){s.planeX=ps.x;s.planeZ=ps.z;s.planeH=ps.heading||0;s.x=ps.x+34;s.z=ps.z+18;s.h=ps.heading||0;let pf=vehicleForward(s.planeH);s.tugX=ps.x+pf[0]*42+18;s.tugZ=ps.z+pf[1]*42+12;s.tugH=s.planeH+Math.PI;this.baseWorld={x:ps.x,z:ps.z,h:ps.heading||0};this.home={x:s.planeX,z:s.planeZ};this.buildQueue()}}
worldFromGate(g){let s=this.state,dx=(g.x-BASE_GATE.x)*this.scale,dz=(g.z-BASE_GATE.z)*this.scale,r=vehicleRight(this.baseWorld.h),f=vehicleForward(this.baseWorld.h);return{x:this.baseWorld.x+r[0]*dx+f[0]*(-dz),z:this.baseWorld.z+r[1]*dx+f[1]*(-dz),h:wrap(this.baseWorld.h+g.heading)}}
localPoint(x,z){let dx=(x-BASE_GATE.x)*this.scale,dz=(z-BASE_GATE.z)*this.scale,r=vehicleRight(this.baseWorld.h),f=vehicleForward(this.baseWorld.h);return{x:this.baseWorld.x+r[0]*dx+f[0]*(-dz),z:this.baseWorld.z+r[1]*dx+f[1]*(-dz)}}
buildQueue(){this.queue=GATES.filter(g=>g.id!==BASE_GATE.id).map(g=>{let w=this.worldFromGate(g);return{id:g.id,lx:g.x,lz:g.z,heading:g.heading,x:w.x,z:w.z,h:w.h}});this.state.extraPlanes=this.queue.map(g=>({id:g.id,x:g.x,z:g.z,h:g.h,visible:true}));this.activeGate=BASE_GATE;this.ui.gate.textContent=this.activeGate.id;this.atcSay('GROUND',`Traffic is active. Additional departures are parked at ${this.queue.map(g=>g.id).join(', ')}.`)}
nose(){let s=this.state,f=vehicleForward(s.planeH);return[s.planeX+f[0]*18.5,s.planeZ+f[1]*18.5]}
hitch(){let s=this.state,f=vehicleForward(s.tugH);return[s.tugX+f[0]*3.45,s.tugZ+f[1]*3.45]}
interact(){let s=this.state;if(!s.ready)return;if(s.mode==='walk'&&dist(s.x,s.z,s.tugX,s.tugZ)<6){s.mode='tug';s.tugSpeed=0;return}if(s.mode==='tug'&&!this.attached){let n=this.nose();if(this.job==='approved'&&dist(s.tugX,s.tugZ,n[0],n[1])<7&&Math.abs(s.tugSpeed)<.7){this.attached=true;this.job='pushback';s.tugSpeed=0;s.tugSteer=0;s.tugH=wrap(s.planeH+Math.PI);let f=vehicleForward(s.tugH);s.tugX=n[0]-f[0]*3.45;s.tugZ=n[1]-f[1]*3.45;let pf=vehicleForward(s.planeH);this.mainGear={x:n[0]-pf[0]*32,z:n[1]-pf[1]*32};this.atcSay('GROUND',`Tug connected Gate ${this.activeGate.id}. Continue approved pushback.`);return}if(dist(s.tugX,s.tugZ,n[0],n[1])>10&&Math.abs(s.tugSpeed)<.4){s.mode='walk';let r=vehicleRight(s.tugH);s.x=s.tugX+r[0]*3;s.z=s.tugZ+r[1]*3;s.h=s.tugH;return}}if(this.attached&&this.job==='release'&&Math.abs(s.towAngle)<10*DEG&&Math.abs(s.tugSpeed)<.5){this.attached=false;this.job='complete';this.mainGear=null;this.taxiT=0;this.makeTaxiPath();this.atcSay('GROUND',`Disconnect approved. Aircraft ${this.activeGate.id} is under its own power. Hold position for the next assignment.`)}}
update(dt){let s=this.state;if(!s.ready)return;this.jobT+=dt;s.mode==='walk'?this.walk(dt):this.drive(dt);if(this.attached)this.tow(dt);if(this.job==='complete')this.taxi(dt);if(this.job==='between')this.nextJob(dt);this.uiUpdate()}
walk(dt){let s=this.state,side=(this.keys.KeyD?1:0)-(this.keys.KeyA?1:0),fore=(this.keys.KeyW?1:0)-(this.keys.KeyS?1:0),l=Math.hypot(side,fore);if(!l)return;side/=l;fore/=l;let cam=Number.isFinite(window.__sbGCCamYaw)?window.__sbGCCamYaw:0,cf=cameraForward(cam),cr=cameraRight(cam),dx=cf[0]*fore+cr[0]*side,dz=cf[1]*fore+cr[1]*side,sp=this.keys.ShiftLeft||this.keys.ShiftRight?8:4.5;s.x+=dx*sp*dt;s.z+=dz*sp*dt;s.h=headingFromForward(dx,dz)}
drive(dt){let s=this.state,gas=this.keys.KeyW?1:0,brake=this.keys.KeyS?1:0,hard=this.keys.Space?1:0,steer=(this.keys.KeyD?1:0)-(this.keys.KeyA?1:0),forwardMax=this.attached?4.6:9.0,reverseMax=this.attached?-3.7:-6.0;if(hard){let dec=17*dt;if(Math.abs(s.tugSpeed)<=dec)s.tugSpeed=0;else s.tugSpeed-=Math.sign(s.tugSpeed)*dec}else if(gas){if(s.tugSpeed<-.12)s.tugSpeed=Math.min(0,s.tugSpeed+11*dt);else s.tugSpeed=Math.min(forwardMax,s.tugSpeed+5.2*dt)}else if(brake){if(s.tugSpeed>.12)s.tugSpeed=Math.max(0,s.tugSpeed-11*dt);else s.tugSpeed=Math.max(reverseMax,s.tugSpeed-4.0*dt)}else{s.tugSpeed*=Math.max(0,1-dt*2.2);if(Math.abs(s.tugSpeed)<.025)s.tugSpeed=0}let steerLimit=this.attached?.42:.55,target=steer*steerLimit;s.tugSteer+=(target-s.tugSteer)*Math.min(1,dt*4.0);if(!steer)s.tugSteer*=Math.max(0,1-dt*4.2);let wheelbase=4.7,turnRate=(s.tugSpeed/wheelbase)*Math.tan(s.tugSteer);s.tugH=wrap(s.tugH+turnRate*dt);let f=vehicleForward(s.tugH);s.tugX+=f[0]*s.tugSpeed*dt;s.tugZ+=f[1]*s.tugSpeed*dt}
tow(dt){let s=this.state,h=this.hitch(),wheelbase=32,noseOffset=18.5;if(!this.mainGear){let pf=vehicleForward(s.planeH);this.mainGear={x:h[0]-pf[0]*wheelbase,z:h[1]-pf[1]*wheelbase}}let vx=h[0]-this.mainGear.x,vz=h[1]-this.mainGear.z,vl=Math.hypot(vx,vz);if(vl<.001)return;let fx=vx/vl,fz=vz/vl,targetH=headingFromForward(fx,fz),dh=wrap(targetH-s.planeH),maxStep=(.35+Math.abs(s.tugSpeed)*.12)*dt;s.planeH=wrap(s.planeH+clamp(dh,-maxStep,maxStep));let pf=vehicleForward(s.planeH);this.mainGear.x=h[0]-pf[0]*wheelbase;this.mainGear.z=h[1]-pf[1]*wheelbase;s.planeX=h[0]-pf[0]*noseOffset;s.planeZ=h[1]-pf[1]*noseOffset;s.towAngle=wrap(s.tugH-(s.planeH+Math.PI));let deg=Math.abs(s.towAngle)/DEG;if(deg>52)s.tugSpeed*=Math.max(0,1-dt*10);if(this.job==='pushback'&&dist(s.planeX,s.planeZ,this.home.x,this.home.z)>48){this.job='release';this.atcSay('GROUND',`Release point reached Gate ${this.activeGate.id}. Straighten the tug, stop, then disconnect.`)}}
makeTaxiPath(){let g=this.activeGate,lx=g.lx??g.x,lz=g.lz??g.z;let route=[{x:lx,z:lz+150},{x:600,z:lz+150},{x:460,z:lz+150},{x:460,z:1800},{x:110,z:1800}].map(p=>this.localPoint(p.x,p.z));this.taxiPath=[{x:this.state.planeX,z:this.state.planeZ},...route];this.taxiIndex=1}
taxi(dt){let s=this.state;this.taxiT+=dt;s.towAngle=0;if(this.taxiT<2)return;if(this.taxiIndex>=this.taxiPath.length){this.finishTaxi();return}let w=this.taxiPath[this.taxiIndex],dx=w.x-s.planeX,dz=w.z-s.planeZ,d=Math.hypot(dx,dz);if(d<8){this.taxiIndex++;return}let target=headingFromForward(dx/d,dz/d),dh=wrap(target-s.planeH),turn=clamp(dh,-.55*dt,.55*dt);s.planeH=wrap(s.planeH+turn);let f=vehicleForward(s.planeH),spd=Math.abs(dh)>.45?5.5:10.5;s.planeX+=f[0]*spd*dt;s.planeZ+=f[1]*spd*dt}
finishTaxi(){this.served.add(this.activeGate.id);this.job='between';this.nextJobT=0;this.state.planeX+=1e6;this.state.planeZ+=1e6;this.atcSay('GROUND',`Aircraft clear of the apron. Stand by — another departure will be assigned shortly.`)}
nextJob(dt){this.nextJobT+=dt;if(this.nextJobT<4)return;let next=this.queue.find(g=>!this.served.has(g.id));if(!next){this.served.clear();this.state.extraPlanes.forEach(p=>p.visible=true);next=this.queue[0]}if(!next)return;this.activeGate=next;let ep=this.state.extraPlanes.find(p=>p.id===next.id);if(ep)ep.visible=false;this.state.planeX=next.x;this.state.planeZ=next.z;this.state.planeH=next.h;this.home={x:next.x,z:next.z};this.mainGear=null;this.taxiPath=[];this.taxiIndex=0;this.job='await';this.jobT=0;this.atcSay('GROUND',`New task: JX-200 at Gate ${next.id}. Drive the tug to the stand and request pushback approval.`)}
uiUpdate(){let s=this.state,deg=Math.abs(s.towAngle/DEG);this.ui.gate.textContent=this.activeGate.id||'—';this.ui.tow.textContent=deg.toFixed(0)+'°';if(this.job==='await'){this.ui.title.textContent=`Stand by · Gate ${this.activeGate.id}`;this.ui.text.textContent='Open ATC and request pushback clearance for the assigned departure.';this.ui.approval.textContent='AWAITING GROUND'}else if(this.job==='approved'){this.ui.title.textContent=`Pushback · Gate ${this.activeGate.id}`;this.ui.text.textContent='Drive to the nose gear. The FRONT of the tug connects to the aircraft. Stop close and press E.';this.ui.approval.textContent='PUSHBACK APPROVED'}else if(this.job==='pushback'){this.ui.title.textContent='Pushback in progress';this.ui.text.textContent=deg>48?'TOW ANGLE TOO HIGH — straighten the tug.':'W drives the tug forward while its FRONT pushes the aircraft back. Keep the tow angle smooth.';this.ui.approval.textContent='TUG CONNECTED'}else if(this.job==='release'){this.ui.title.textContent='Release point reached';this.ui.text.textContent='Straighten, stop, then press E to disconnect.';this.ui.approval.textContent='READY TO RELEASE'}else if(this.job==='complete'){this.ui.title.textContent='Aircraft taxiing';this.ui.text.textContent='NPC control has taken over. It is following the apron lane and taxiway toward the runway.';this.ui.approval.textContent='JOB COMPLETE'}else{this.ui.title.textContent='Stand by for next aircraft';this.ui.text.textContent='Another parked departure will be assigned in a moment.';this.ui.approval.textContent='TURNAROUND'}let p='';if(s.mode==='walk'&&dist(s.x,s.z,s.tugX,s.tugZ)<6)p='E · ENTER TUG';if(s.mode==='tug'&&!this.attached&&this.job==='approved'){let n=this.nose();if(dist(s.tugX,s.tugZ,n[0],n[1])<7)p='E · CONNECT FRONT TUG TO NOSE GEAR'}if(this.attached&&this.job==='release'&&deg<10&&Math.abs(s.tugSpeed)<.5)p='E · DISCONNECT';this.ui.prompt.textContent=p;this.ui.prompt.classList.toggle('show',!!p)}
frame(t){if(!this.running)return;let dt=Math.min(.033,(t-this.last)/1000||.016);this.last=t;this.update(dt);requestAnimationFrame(n=>this.frame(n))}}
export function startGroundCrew(opts={}){document.body.classList.add('gc-same-world');return new GroundCrew(opts)}window.SkyboundGroundCrew={start:startGroundCrew};
